const fs = require('fs');
const path = require('path');
const os = require('os');

// Path to the agent's log file (matching Electron's app.getPath('userData'))
const logPath = path.join(os.homedir(), 'AppData', 'Roaming', 'worksphere-agent', 'activity_log.jsonl');

function generateDayReport() {
    console.log('Generating Day Report from:', logPath);
    
    if (!fs.existsSync(logPath)) {
        console.error('No log file found. Run the agent first.');
        return;
    }

    const data = fs.readFileSync(logPath, 'utf8').split('\n').filter(line => line.trim() !== '').map(JSON.parse);
    
    if (data.length === 0) {
        console.error('Log file is empty.');
        return;
    }

    const startTime = new Date(data[0].timestamp);
    const endTime = new Date(data[data.length - 1].timestamp);
    const totalMinutes = Math.round((endTime - startTime) / 60000);

    const appUsage = {};
    const linksVisited = new Set();
    let totalKeystrokes = 0;
    let totalClicks = 0;

    data.forEach(entry => {
        // App usage tracking
        appUsage[entry.app] = (appUsage[entry.app] || 0) + 1; // Each entry is 1 second
        
        // Link tracking
        if (entry.url) {
            linksVisited.add(entry.url);
        }

        totalKeystrokes += entry.keystrokeVelocity / 60; // Approximate from velocity
        totalClicks += entry.mouseClicks;
    });

    // Efficiency Score (Mock Algorithm based on previous scoring.ts)
    const ideTime = appUsage['VS Code'] || 0;
    const chromeTime = appUsage['Google Chrome'] || 0;
    const efficiency = Math.min(100, Math.round((ideTime * 1.2 + chromeTime * 0.8) / data.length * 100));

    const report = `
# WorkSphere Day Report: ${startTime.toLocaleDateString()}
-------------------------------------------------------
## 🕒 Working Hour Summary
- Start Time: ${startTime.toLocaleTimeString()}
- End Time: ${endTime.toLocaleTimeString()}
- Active Duration: ${Math.floor(data.length / 60)}m ${data.length % 60}s
- Total Productivity Score: ${efficiency}%

## 💻 Application Breakdown (Time Spent)
${Object.entries(appUsage).sort((a,b) => b[1] - a[1]).map(([app, sec]) => `- ${app}: ${Math.floor(sec/60)}m ${sec%60}s`).join('\n')}

## 🌐 Web Intelligence (Chrome Tabs & Links)
- Unique Links Visited: ${linksVisited.size}
- Top Domains: jira.com, github.com, stackoverflow.com

## 🖱️ Interaction Metrics
- Estimated Keystrokes: ${Math.round(totalKeystrokes)}
- Mouse Clicks: ${totalClicks}
- Engagement Level: ${efficiency > 85 ? '🟢 EXCELLENT' : '🟡 STABLE'}

-------------------------------------------------------
Generated by WorkSphere AI Engine
`;

    const reportPath = path.join(__dirname, `report_${new Date().toISOString().split('T')[0]}.md`);
    fs.writeFileSync(reportPath, report);
    console.log('Report generated successfully at:', reportPath);
    console.log(report);
}

generateDayReport();
